# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Góc của T.Anh
email: anhdt0407@gmail.com
author: Đinh Tuấn Anh
permalink: ':title:output_ext'
description: 'Góc của T.Anh' # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://anhdt2511.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/MVM-logo-full.svg"
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/MVM-logo-full-dark.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Đinh Tuấn Anh # add your name
author-pic: Myself_Neon_grey.jpg
about-author: Xin chào, mình là Tuấn Anh. Đây là nơi mình chia sẽ các bài viết về lập trình và tất cả thể loại mà mình thích viết, còn viết khi nào thì tuỳ hứng.

# Contact links
email: anhdt0407@gmail.com # Add your Email address
phone: # Add your Phone number
website: https://anhdt.dev # Add your website
linkedin: # Add your Linkedin handle
github: anhdt2511 # Add your Github handle
twitter: # Add your Twitter handle
facebook: s2.mask

# Newsletter

# Disqus
discus_identifier: anhdt2511-github-io # Add your discus identifier
comments_curtain: yes # leave empty to show the disqus embed directly

# Tracker
analytics: G-XM9T80G9QJ
fbadmin: s2.mask

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 100

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: VN # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

highlight_theme: syntax-base16.solarized.dark # select a theme for the code highlighter

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]